services:
  # ======================================================================
  # 1. BANCO DE DADOS (POSTGRESQL)
  # ======================================================================
  postgres:
    image: postgres:15.3-alpine
    container_name: cont-wallet-postgres
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432" 
    deploy:
      resources:
        limits:
          memory: 640M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wallet_network

  # ======================================================================
  # 2. COLETORES DE DADOS (JAEGER E LOKI)
  # ======================================================================
  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: cont-wallet-jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      TZ: America/Sao_Paulo
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250" # Porta nativa gRPC (Model)
      - "14269:14269" # Porta Admin/Health Check
    volumes:
      - jaeger_tracing_data:/var/lib/jaeger
    networks:
      - wallet_network

  loki:
    image: grafana/loki:2.9.0
    container_name: cont-wallet-loki
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - wallet_network

  # ======================================================================
  # 3. OPEN TELEMETRY COLLECTOR
  # ======================================================================
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    container_name: cont-wallet-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      jaeger:
        condition: service_started
      loki:
        condition: service_started
      tempo:
        condition: service_started
    networks:
      - wallet_network

  # ======================================================================
  # 4. MONITORAMENTO (PROMETHEUS E GRAFANA)
  # ======================================================================
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: cont-wallet-prometheus
    restart: unless-stopped
    environment:
      PROM_PROFILE: local # use homolog/prod conforme o ambiente
    volumes:
      #- ./prometheus/prometheus-${PROM_PROFILE:-local}.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      otel-collector:
        condition: service_started
    networks:
      - wallet_network

  grafana:
    image: grafana/grafana:10.2.3
    container_name: cont-wallet-grafana
    restart: unless-stopped
    user: "472"
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    networks:
      - wallet_network

  # ======================================================================
  # 5. APLICAÇÃO WALLET SERVICE
  # ======================================================================
  wallet-service-api:
    image: wallet-service-api:latest
    build: .
    container_name: cont-wallet-service-api
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      SPRING_PROFILES_ACTIVE: homolog
      SPRING_CLOUD_VAULT_ENABLED: "true"
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: root
      SPRING_CLOUD_VAULT_KV_ENABLED: "true"
      SPRING_CLOUD_VAULT_KV_BACKEND: secret
      SPRING_CLOUD_VAULT_KV_APPLICATION_NAME: wallet-service-api
      SPRING_CLOUD_VAULT_KV_PROFILES: homolog
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
      MANAGEMENT_OTLP_LOGGING_ENDPOINT: http://otel-collector:4318/v1/logs
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://otel-collector:4318/v1/traces
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,loggers,prometheus,metrics,caches,cache,threaddump,httpexchanges" 
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
      vault:
        condition: service_healthy
    volumes:
      - wallet_service_data:/app/data
      - ./data/seed:/app/data/seed
      - ./security-matchers.yml:/app/config/security-matchers.yml
    networks:
      - wallet_network

  # ======================================================================
  # UTILITÁRIOS
  # ======================================================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: cont-wallet-pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: wallet_pass
    depends_on:
      - postgres
    networks:
      - wallet_network

  runner-act:
    image: catthehacker/ubuntu:act-20.04
    container_name: cont-wallet-runner-act
    restart: "no"
    tty: true
    stdin_open: true
    volumes:
      - runner_act_data:/var/lib/runner_act/data
    networks:
      - wallet_network

  # Para habilitar essas métricas no seu Grafana, você deve adicionar o cAdvisor
  cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.47.0
      container_name: cont-wallet-cadvisor
      restart: unless-stopped
      privileged: true
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      ports:
        - "8085:8080"
      networks:
        - wallet_network

  vault:
    image: hashicorp/vault:1.15
    container_name: cont-wallet-vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_TOKEN: "root"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD-SHELL", "vault kv get secret/wallet-service-api/homolog || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c '
      vault server -dev -dev-listen-address="0.0.0.0:8200" &
      sleep 5;
      vault kv put secret/wallet-service-api/homolog spring.datasource.url="jdbc:postgresql://postgres:5432/wallet_db" spring.datasource.username="wallet_user" spring.datasource.password="wallet_pass" jwt.secret="mock-key-super-secret-jwt.2J8320JRF329FJ23JF9239FHF2F923HF9823HF98238F";
      wait
      '
    networks:
      - wallet_network

  # ======================================================================
  # 7. TEMPO - TRACING BACKEND
  # ======================================================================
  tempo:
    image: grafana/tempo:latest
    container_name: cont-wallet-tempo
    restart: unless-stopped
    ports:
      - "3200:3200"
      #- "4317" # OTLP gRPC
      #- "4318" # OTLP HTTP
    networks:
      - wallet_network
    command: >
      -target=all
      -storage.trace.backend=local
      -storage.trace.local.path=/tmp/tempo/traces


  # ======================================================================
  # SONAR QUBE
  # ======================================================================
  sonarqube:
    image: sonarqube:10-community
    container_name: cont-wallet-sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - wallet_network


# ======================================================================
# VOLUMES
# ======================================================================
volumes:
  postgres_data:
  wallet_service_data:
  jaeger_tracing_data:
  runner_act_data:
  pgadmin_data:
  grafana-data:
  loki-data:
  sonarqube_data:
  sonarqube_extensions:

# ======================================================================
# NETWORK
# ======================================================================
networks:
  wallet_network:
    driver: bridge
