receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

  memory_limiter:
    check_interval: 5s
    limit_mib: 500
    spike_limit_mib: 100

  resource:
    attributes:
      - key: service.name
        value: wallet-service-api
        action: insert
      - key: job
        value: "cont-${APP_NAME}"
        action: insert
      - key: container_name
        value: "cont-${APP_NAME}"
        action: insert
      - key: env
        value: "env-local"
        action: insert

connectors:
  spanmetrics:
    namespace: traces_span_metrics
    metrics_flush_interval: 15s
    histogram:
      explicit:
        buckets: [5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s]
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.status_code

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  otlphttp/jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: true
      job: true
      instance: true

  logging:
    verbosity: detailed

  # Exporta traces pro Tempo via OTLP gRPC na rede Docker.
  # Use o NOME DO SERVIÇO/CONTAINER que está na mesma network do collector.
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  #otlp/tempo:
  #  endpoint: tempo:4317
  #  tls:
  #    insecure: true

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [spanmetrics, otlphttp/tempo, otlphttp/jaeger, logging]

    metrics:
      receivers: [spanmetrics, otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, logging]

