receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

  memory_limiter:
    check_interval: 5s
    limit_mib: 400
    spike_limit_mib: 100

  # Adiciona metadados úteis para você filtrar no Grafana depois
  resource:
    attributes:
      - key: service.name
        value: wallet-service-api
        action: insert
      - key: deployment.environment
        value: "kind-local"
        action: insert

connectors:
  spanmetrics:
    namespace: traces_span_metrics
    metrics_flush_interval: 15s
    histogram:
      explicit:
        buckets: [5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2s, 5s]
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.status_code

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  # Jaeger via OTLP/HTTP (Porta 4318)
  otlphttp/jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

  # Loki (Versão moderna via OTLP)
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp/v1/logs"
    tls:
      insecure: true

  # Tempo via OTLP/HTTP (Porta 4318)
  otlphttp/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true

  logging:
    verbosity: basic # Troque para 'detailed' se precisar debugar a chegada dos dados

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [spanmetrics, otlphttp/tempo, otlphttp/jaeger, logging]

    metrics:
      receivers: [spanmetrics, otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/loki, logging]