apiVersion: v1
kind: Secret
metadata:
  name: wallet-api-secrets
type: Opaque
stringData:
  # Valores estáticos para ambiente Kind (sem Vault)
  spring.datasource.url: jdbc:postgresql://postgres:5432/wallet_db
  spring.datasource.username: wallet_user
  spring.datasource.password: wallet_pass
  jwt.secret: mock.jwt.secret.docker.k8s.value_8235hu23523h523h57823h58723h823
  # Credenciais do próprio banco se necessário
  postgres-user: wallet_user
  postgres-password: wallet_pass
