apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: NodePort
  selector:
    app: tempo
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: ui
      port: 3200
      targetPort: 3200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.10.3
        # O argumento que aponta para o arquivo que vamos montar
        args: ["-config.file=/etc/tempo.yaml"]
        ports:
          - containerPort: 4317 # gRPC para Traces
          - containerPort: 4318 # HTTP para Traces (usado pela sua API)
          - containerPort: 3200 # HTTP para a UI do Tempo/Grafana
        volumeMounts:
          - name: tempo-config-volume
            mountPath: /etc/tempo.yaml
            subPath: tempo.yaml # Monta como ARQUIVO dentro de /etc/
          - name: tempo-data
            mountPath: /tmp/tempo
      volumes:
        - name: tempo-config-volume
          configMap:
            name: tempo-conf # Nome do ConfigMap que contÃ©m seu arquivo local
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-data-pvc
