auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# NA V3.x, TENTE HABILITAR O OTLP DENTRO DO LIMITS_CONFIG
# OU REMOVA O BLOCO OTLP SE ELE CONTINUAR DANDO ERRO DE PARSE
limits_config:
  allow_structured_metadata: true

# ESTRUTURA COMPATÍVEL V3.5
schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h