# =========================
# Vars usadas por placeholders (bootstrapping)
# =========================
APP_NAME: wallet-service-api
PROFILE: local
API_PREFIX: /api/v1
ENV: env-local
WALLET_USER: wallet_user
WALLET_PASS: wallet_pass
JWT_SECRET: mock.jwt_token.profile_test.859jg89045j9045i
MANAGEMENT_OTLP_ENDPOINT: http://localhost:4317


###############################
###############################
###############################
###############################

app:
  api-prefix: ${API_PREFIX}
  seeder:
    enabled: true # Mude para true para executar a carga na inicialização

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /${APP_NAME}

spring:
  application:
    name: ${APP_NAME}
  # Desativa o cache do OpenAPI (SpringDoc)
  cache.disabled: true    
  config:
    import: 
      - "optional:classpath:security-matchers.yml"
      ##- "optional:vault://v1/secret/data/${APP_NAME}/${PROFILE}"
      ##- "optional:vault://secret/${APP_NAME}/${PROFILE}"
    active:
      on-profile: ${PROFILE}
  cloud:
    bootstrap:
      enabled: false  # Desativa o carregamento do bootstrap.yml
    vault:
      enabled: false
      ssl:
        enabled: false

  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 150
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
        "[format_sql]": true
        "[use_sql_comments]": true
        jdbc:
          "[batch_size]": 1000
        "[order_inserts]": true
        "[order_updates]": true
        jdbc.batch_versioned_data: true
  otlp:
    logs:
      enabled: true # Força o auto-appender
      endpoint: http://otel-collector:4318/v1/logs # Endpoint específico de logs
  threads:
    virtual:
      enabled: true # Opcional, mas recomendado para Java 21+

springdoc:
  #paths-to-match: "${API_PREFIX}/**"
  packages-to-scan: com.guga.walletserviceapi.controller  
  show-actuator: true
  writer-with-default-pretty-printer: true

  api-docs:
    path: /v3/api-docs

  api-responses:
    - key: BadRequest
      description: Invalid request
    - key: NotFound
      description: Resource not found
    - key: Conflict
      description: Conflict occurred
    - key: InternalError
      description: Unexpected error


  info:
    title: Wallet Service API
    version: '@project.version@' # Pega a versão do pom.xml automaticamente
    description: |
      Documentação da API de Carteira de Clientes.

      ---

      ### 🔑 Autenticação (A partir da v0.2.4)

      A autenticação agora utiliza **JSON Web Tokens (JWT)**. Para acessar os endpoints protegidos, siga os passos abaixo:

      1.  **Obter o Token:**
          * Execute o endpoint de login: **`POST /api/auth/login`**.
          * Use suas credenciais de usuário e senha no corpo da requisição (Request Body).

      2.  **Autorizar o Swagger (OpenAPI):**
          * Copie o **token JWT** retornado no campo `access_token`.
          * Clique no botão **"Authorize"** (Autorizar) no topo da página.
          * Cole o token no campo de autenticação (Geralmente no formato **`Bearer SeuTokenAqui`**).

      3.  **Executar Métodos:**
          * Com o token configurado no Swagger, você pode executar todos os métodos protegidos.

      ---

      **Credenciais de Teste:**
      * **Usuário:** `wallet_user`
      * **Senha:** `wallet_pass`

  ordered-tags:
    - name: "Authenticator"
    - name: "ParamApp"
    - name: "Customers"
    - name: "Wallet"
    - name: "Transaction"
    - name: "WalletOperator"
    - name: "Seed"

  # sql.init.mode: none

  swagger-ui:
    path: /swagger-ui.html
    displayOperationId: true # Garante que o operationId seja visível
    try-it-out-enabled: 'false'
    operationsSorter: operationId # Define a ordenação por operationId
    custom-js: /swagger-ui/custom.js

management:
  endpoints:
    web:
      exposure:
        include: "*" # Cuidado em prod, mas perfeito para local/debug
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true # novo padrão recomendado

  # --- Configuração OTLP (Logs, Traces e Metrics) ---
  otlp:
    logs:
      endpoint: "http://otel-collector:4318/v1/logs"
    tracing:
      endpoint: "http://otel-collector:4318/v1/traces"
    metrics:
      export:
        url: "http://otel-collector:4318/v1/metrics"
        step: 10s

logging:
  # Mantive seus redirecionamentos de saída
  stderr:
    level: DEBUG
  stdout:
    level: DEBUG
  file:
    name: logs/${APP_NAME:wallet-service-api}-${PROFILE}.log
  exception-conversion-word: "%wEx{5}"  
  level:
    # --- Raiz e Projeto ---
    root: INFO
    com.guga.walletserviceapi: INFO
    com.guga.walletserviceapi.security: INFO

    # --- opentelemetry --
    io.opentelemetry: INFO
    io.opentelemetry.exporter.otlp: INFO

    # --- Silenciamento (Actuator/Tomcat) ---
    org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping: INFO
    org.springframework.boot.context.config: INFO
    org.apache.tomcat.util.http.Parameters: INFO

    # --- Spring Web e Endpoints (Seus Debugs Específicos) ---
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO

    # --- Spring Security (Sua rastreabilidade de filtros) ---
    org.springframework.security: INFO
    org.springframework.security.web.FilterChainProxy: INFO
    org.springframework.security.web.authentication.AnonymousAuthenticationFilter: INFO

    # --- Infraestrutura e Testes ---
    org.springframework.test: INFO
    org.springframework.core.env: INFO
    org.hibernate: INFO

    # --- Cloud, Vault e OTel (Corrigidos para o nível certo) ---
    org.springframework.vault.core.env: INFO
    org.springframework.cloud.vault: INFO
    org.springframework.cloud.vault.config: INFO
    org.springframework.vault: INFO
    org.springframework.vault.client: INFO
    org.springframework.boot.actuate.autoconfigure.logging.otlp: INFO

    # --- Seu Filtro Customizado (Jwt) ---
    # com.guga.walletserviceapi.security.JwtAuthenticationFilter: ERROR

