# =========================
# Vars usadas por placeholders (bootstrapping)
# =========================
APP_NAME: wallet-service-api
PROFILE: local
API_PREFIX: /api/v1
ENV: env-local
WALLET_USER: wallet_user
WALLET_PASS: wallet_pass
JWT_SECRET: mock.jwt_token.profile_test.859jg89045j9045i
MANAGEMENT_OTLP_ENDPOINT: http://localhost:4317


app:
  seeder:
    enabled: true # Mude para true para executar a carga na inicialização

spring:
  config:
    import: 
      - "optional:classpath:security-matchers.yml"
      - "optional:vault://secret/${APP_NAME}/${PROFILE}"
  cloud:
    vault:
      enabled: true
      #host: localhost
      scheme: http
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
        version: 2
        default-context: wallet-service-api
        profiles: ${PROFILE:local}
        profile-separator: /
      config:
        order: 1
      kv-version: 2
      ssl:
        enabled: false
    bootstrap:
      enabled: false
      
  #datasource:
  #  url: jdbc:postgresql://cont-wallet-postgres:5432/wallet_db
  #  driver-class-name: org.postgresql.Driver
  #  username: wallet_user
  #  password: wallet_pass

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    user:
      name: ${WALLET_USER:wallet_user}
      password: ${WALLET_PASS:wallet_pass}
      roles:
        - ADMIN
        - USER
