spring:
  config:
    import: 
      - "optional:classpath:security-matchers.yml"
      - "optional:vault://v1/secret/data/${APP_NAME}/${PROFILE}"
  cloud:
    vault:
      enabled: false
      #uri: http://localhost:8200
      #authentication: TOKEN
      #token: root
      #scheme: http
      #kv:
      #  enabled: true
      #  backend: secret
      #  version: 2
      #  #authentication: TOKEN
      #  default-context: wallet-service-api
      #  profiles: ${PROFILE:local}
    #bootstrap:
    #  enabled: false
      
  #datasource:
  #  url: jdbc:postgresql://host.docker.internal:5432/wallet_db
  #  driver-class-name: org.postgresql.Driver
  #  username: wallet_user
  #  password: wallet_pass

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    user:
      name: ${WALLET_USER:wallet_user}
      password: ${WALLET_PASS:wallet_pass}
      roles:
        - ADMIN
        - USER

