# =========================
# Vars usadas por placeholders (bootstrapping)
# =========================
APP_NAME: wallet-service-api
PROFILE: local
API_PREFIX: /api/v1
ENV: env-local
WALLET_USER: wallet_user
WALLET_PASS: wallet_pass
JWT_SECRET: mock.jwt_token.profile_test.859jg89045j9045i
MANAGEMENT_OTLP_ENDPOINT: http://localhost:4317


###############################
###############################
###############################
###############################

app:
  api-prefix: ${API_PREFIX}
  seeder:
    enabled: false # Mude para true para executar a carga na inicialização

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /${APP_NAME}

spring:
  application:
    name: ${APP_NAME}
  # Desativa o cache do OpenAPI (SpringDoc)
  cache.disabled: true    
  config:
    import: 
      - "optional:classpath:security-matchers.yml"
      ##- "optional:vault://secret/${APP_NAME}/${PROFILE}"
      ##- "optional:vault://secret/${APP_NAME}/${PROFILE}"
    active:
      on-profile: local
  cloud:
    bootstrap:
      enabled: false  # Desativa o carregamento do bootstrap.yml
    vault:
      enabled: false
      ssl:
        enabled: false
      #authentication: TOKEN
      #kv:
      #  enabled: true
      #  backend: secret
      #  version: 2
      #  default-context: ${APP_NAME}
      #  profiles: ${PROFILE:local}
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 150
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
        "[format_sql]": true
        "[use_sql_comments]": true
        jdbc:
          "[batch_size]": 1000
        "[order_inserts]": true
        "[order_updates]": true
        jdbc.batch_versioned_data: true
  #mvc:
    #servlet:
      #path: /api/v1

springdoc:
  #paths-to-match: "${API_PREFIX}/**"
  packages-to-scan: com.guga.walletserviceapi.controller  
  show-actuator: true
  writer-with-default-pretty-printer: true

  api-docs:
    path: /v3/api-docs

  api-responses:
    - key: BadRequest
      description: Invalid request
    - key: NotFound
      description: Resource not found
    - key: Conflict
      description: Conflict occurred
    - key: InternalError
      description: Unexpected error


  info:
    title: Wallet Service API
    version: '@project.version@' # Pega a versão do pom.xml automaticamente
    description: |
      Documentação da API de Carteira de Clientes.

      ---

      ### 🔑 Autenticação (A partir da v0.2.4)

      A autenticação agora utiliza **JSON Web Tokens (JWT)**. Para acessar os endpoints protegidos, siga os passos abaixo:

      1.  **Obter o Token:**
          * Execute o endpoint de login: **`POST /api/auth/login`**.
          * Use suas credenciais de usuário e senha no corpo da requisição (Request Body).

      2.  **Autorizar o Swagger (OpenAPI):**
          * Copie o **token JWT** retornado no campo `access_token`.
          * Clique no botão **"Authorize"** (Autorizar) no topo da página.
          * Cole o token no campo de autenticação (Geralmente no formato **`Bearer SeuTokenAqui`**).

      3.  **Executar Métodos:**
          * Com o token configurado no Swagger, você pode executar todos os métodos protegidos.

      ---

      **Credenciais de Teste:**
      * **Usuário:** `wallet_user`
      * **Senha:** `wallet_pass`

  ordered-tags:
    - name: "Authenticator"
    - name: "ParamApp"
    - name: "Customers"
    - name: "Wallet"
    - name: "Transaction"
    - name: "WalletOperator"
    - name: "Seed"

  # sql.init.mode: none

  swagger-ui:
    path: /swagger-ui.html
    displayOperationId: true # Garante que o operationId seja visível
    try-it-out-enabled: 'false'
    operationsSorter: operationId # Define a ordenação por operationId
    custom-js: /swagger-ui/custom.js
    #tagsSorter: none
    ## groups-order: ASC
  #use-root-path: true


management:
  endpoints:
    web:
      exposure:
        include: "startup,health,info,loggers,prometheus,metrics,caches,cache,threaddump,httpexchanges,env"
      base-path: /actuator
  endpoint:
    startup:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  info:
    build:
      enabled: true # Expõe versão, artifactId, time do build
    git:
      mode: full    # Expõe commit hash, branch, mensagem
    env:
      enabled: true # Expõe variáveis de ambiente seguras (opcional)
  observations:
    key-values:
      application: ${APP_NAME}
  prometheus:
    metrics:
      export:
        enabled: true
  otlp:
    logging:
      endpoint: ${MANAGEMENT_OTLP_ENDPOINT}/logs
      timeout: 90s
    tracing:
      endpoint: ${MANAGEMENT_OTLP_ENDPOINT}/traces
      timeout: 90s
    metrics:
      export:
        enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      process: true
      jvm: true
    tags:
      application: ${APP_NAME}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    skip-pattern: /actuator/**, /swagger-ui/**, /v3/api-docs/**

logging:
  # Garante que o log saia no terminal/console do seu IDE
  stderr:
    level: DEBUG
  stdout:
    level: DEBUG
  file:
    name: logs/${APP_NAME:wallet-service-api}.log
  exception-conversion-word: "%wEx{5}"
  level:
    # --- Raiz e Projeto ---
    root: DEBUG
    com.guga.walletserviceapi: DEBUG
    com.guga.walletserviceapi.security: DEBUG

    # --- Silencia os logs de /actuator/prometheus ---
    org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping: ERROR
    #org.apache.tomcat.util.http.Parameters: ERROR    # Se quiser silenciar o log de acesso do servidor (se estiver ativado)

    # --- Spring Web e Endpoints ---
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG

    # --- Spring Security ---
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication.AnonymousAuthenticationFilter: DEBUG    

    # --- Infraestrutura e Testes ---
    org.springframework.test: DEBUG
    org.springframework.core.env: DEBUG
    org.hibernate: INFO

    # --- Cloud e Vault ---
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG


    # Silencia o SEU filtro customizado (JwtAuthenticationFilter)
    # Substitua o pacote pelo caminho real da sua classe
    # logging.level.com.github.w.s.f.JwtAuthenticationFilter: ERROR


