# =========================
# Vars usadas por placeholders (bootstrapping)
# =========================
APP_NAME: wallet-service-api
PROFILE: dev
API_PREFIX: /api/v1
ENV: env-dev
WALLET_USER: wallet_user
WALLET_PASS: wallet_pass
JWT_SECRET: mock.jwt_token.profile_test.859jg89045j9045i
MANAGEMENT_OTLP_ENDPOINT: http://localhost:4317


app:

  seeder:
    enabled: false # Mude para true para executar a carga na inicialização


spring:
  config:
    import: 
      - "optional:classpath:security-matchers.yml"
      - "optional:vault://v1/secret/data/${APP_NAME}/${PROFILE}"
  cloud:
    vault:
      enabled: false
      #uri: http://localhost:8200
      #authentication: TOKEN
      #token: root
      #scheme: http
      #kv:
      #  enabled: true
      #  backend: secret
      #  version: 2
      #  #authentication: TOKEN
      #  default-context: wallet-service-api
      #  profiles: ${PROFILE:dev}
    #bootstrap:
    #  enabled: false
      
  datasource:
    # Configuração para H2 via arquivo
    #url: jdbc:h2:mem:wallet-test-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    url: jdbc:h2:file:./data/h2/wallet-dev-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: ${WALLET_USER:wallet_user}
    password: ""
    #password: ${WALLET_PASS:wallet_pass}

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    user:
      name: ${WALLET_USER:wallet_user}
      password: ${WALLET_PASS:wallet_pass}
      roles:
        - ADMIN
        - USER

logging:
  file:
    name: logs/${APP_NAME:wallet-service-api}-dev.log