name: 🧠 SonarQube Analysis

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]
  workflow_dispatch:

jobs:
  sonar:
    name: 🔍 SonarQube Quality Scan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [ desenv, cloud ]

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: 🔨 Build and analyze
        run: |
          if [ "${{ matrix.profile }}" == "desenv" ]; then
            ./mvnw clean verify sonar:sonar -DskipTests \
              -Dsonar.login=admin \
              -Dsonar.password=admin123 \
              -Dsonar.host.url=http://localhost:9000 \
              -P desenv
          else
            ./mvnw clean verify sonar:sonar -DskipTests -X \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -P cloud
          fi