name: 🧠 SonarQube Analysis

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  sonar:
    name: 🔍 SonarQube Quality Scan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [ desenv, cloud ]


    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # O Sonar exige histórico completo (full git history)

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      # NOVO PASSO DE DEBUG
      - name: Debug #: Imprimir Valores de Configuração
        run: |
          echo "Verificando as chaves de configuração (Valores sensíveis são mascarados):"
          echo "PROJECT KEY: ${{ secrets.SONAR_PROJECT_KEY }}"
          echo "ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}"
          echo "HOST URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "SONAR TOKEN: ${{ secrets.SONAR_TOKEN }}" # Será mascarado
        shell: bash


      - name: 🔨 Build and analyze
        #env:
        #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ "${{ matrix.profile }}" == "desenv" ]; then
            ./mvnw clean verify sonar:sonar -DskipTests \
              -Dsonar.login=admin \
              -Dsonar.password=admin123 \
              -Dsonar.host.url=http://localhost:9000 \
              -P desenv
          else
            ./mvnw clean verify sonar:sonar -DskipTests -X \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -P cloud
          fi