server:
  port: '8080'
controller:
  path:
    base: "/wallet-services-api/api"
spring:
  datasource:
    url: jdbc:h2:mem:wallet_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: wallet_user
    password: wallet_pass
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  application:
    name: wallet-service
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 200
        page-parameter: page
        size-parameter: size

logging:
  level:
    org:
      springframework: DEBUG
    root: INFO
