controller:
  path:
    base: "/wallet-services-api/api"
springdoc:
  info:
    title: Microservices Wallet Service
    description: API REST manages the entire lifecycle of a wallet service
  swagger-ui:
    server-url: ${SERVER_URL}/wallet-services
    path: /swagger-ui.html
    try-it-out-enabled: 'false'
  api-docs:
    path: /v3/api-docs
    enabled: true
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/wallet_db
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver
    # initialization-mode: always
    # Uncomment below to use H2 Database instead of PostgreSQL
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:file:~/dados/wallet_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    #username: wallet_user
    #password: wallet_pass
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 200
        page-parameter: page
        size-parameter: size

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org:
      springframework: DEBUG
    root: INFO
server:
  port: '8080'
