server:
  port: '8080'
controller:
  path:
    base: "/wallet-services-api/api"
springdoc:
  info:
    title: Microservices Wallet Service
    description: API REST manages the entire lifecycle of a wallet service
  swagger-ui:
    server-url: ${SERVER_URL}/wallet-services-api
    path: /swagger-ui.html
    try-it-out-enabled: 'false'
    #persistAuthorization: true
    #displayOperationId: false
    # 4. Outras customizações comuns (opcional)
    groups-order: ASC
    #operationsSorter: method


  api-docs:
    path: /v3/api-docs
    enabled: true
spring:
  application:
    name: wallet-service-api
  datasource:
    #url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    url: jdbc:h2:file:~/dados/wallet_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: wallet_user
    password: wallet_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 200
        page-parameter: page
        size-parameter: size
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: 'DEBUG'
      hibernate:
        SQL: DEBUG
    root: INFO
