{
 "title": "HTTP Metrics OpenTelemetry",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "query": { "query": "label_values(environment)" } },
   { "name": "route", "query": { "query": "label_values(http_route)" } },
   { "name": "http_method", "query": { "query": "label_values(http_method)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_sum{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval])) by (environment, http_route, http_method) /\navg(rate(http_server_requests_seconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval])) by (environment, http_route, http_method)",
     "legendFormat": "{{env}} {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Top Requests Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_route, http_method)",
     "legendFormat": "{{env}} {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Top Requests Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_route, http_method)",
     "legendFormat": "{{env}} {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval])) by (agent, http_route, http_method)) * $__interval_ms / 1000",
     "legendFormat": "{{env}} {{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Requests statistics",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\",  http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"2..\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"3..\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"4..\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\", http_status_code=~\"5..\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{environment=~\"${env}\",  http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval]) * $__interval_ms / 1000) by (agent, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "(sum(rate(http_server_duration_milliseconds_sum{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval])) by(agent, http_method, http_route) / sum(rate(http_server_duration_milliseconds_count{environment=~\"${env}\", http_route=~\"${route}\", http_method=~\"${http_method}\"}[$__rate_interval])) by(agent, http_method, http_route) >= 0) OR on() vector(0)",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{environment=~\"${env}\", job=~\"${Job}\", path=~\"${route}\", method=~\"${http_method}\", status_code=~\"4xx|5xx\"}[$__rate_interval])) by (agent, job, path, method)",
     "legendFormat": "{{env}} {{method}} {{path}}"
    }
   ]
  }
 ]
}