{
 "title": "Scraping",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(scraparr_services_up,job)"
    }
   },
   {
    "name": "prowlarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"prowlarr\"},alias)"
    }
   },
   {
    "name": "sonarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"sonarr\"},alias)"
    }
   },
   {
    "name": "radarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"radarr\"},alias)"
    }
   },
   {
    "name": "bazarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"bazarr\"},alias)"
    }
   },
   {
    "name": "readarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"readarr\"},alias)"
    }
   },
   {
    "name": "seerr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"seerr\"},alias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Seerr ${seerr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "seerr" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"seerr\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_user_total{job=~\"$job\", alias=\"$seerr\"} or overseerr_user_total{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (jellyseerr_last_scrape{job=~\"$job\", alias=\"$seerr\"} or overseerr_last_scrape{job=~\"$job\", alias=\"$seerr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issue Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Issues" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_issue_status{job=~\"$job\", alias=\"$seerr\"} or overseerr_issue_status{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issue Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Issues" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_issue_total{job=~\"$job\", alias=\"$seerr\"} or overseerr_issue_total{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_request_status{job=~\"$job\", alias=\"$seerr\"} or overseerr_request_status{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_request_total{job=~\"$job\", alias=\"$seerr\"} or overseerr_request_total{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jellyseerr_request_tv{job=~\"$job\", alias=\"$seerr\"} or overseerr_request_tv{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jellyseerr_request_movie{job=~\"$job\", alias=\"$seerr\"} or overseerr_request_movie{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jellyseerr_request_seasons_total{job=~\"$job\", alias=\"$seerr\"} or overseerr_request_seasons_total{job=~\"$job\", alias=\"$seerr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issue Type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Issues" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_issue_type{job=~\"$job\", alias=\"${seerr}\"} or overseerr_issue_type{job=~\"$job\", alias=\"${seerr}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issue Media Type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Issues" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_issue_media_type{job=~\"$job\", alias=\"${seerr}\"} or overseerr_issue_media_type{job=~\"$job\", alias=\"${seerr}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issue Media Type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Issues" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyseerr_issue_and_media_type{job=~\"$job\", alias=\"${seerr}\"} or overseerr_issue_and_media_type{job=~\"$job\", alias=\"${seerr}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Readarr ${readarr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "readarr" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"readarr\", alias=\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_build_time{job=~\"$job\", alias=\"$readarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - readarr_last_scrape{job=~\"$job\", alias=\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - readarr_start_time{job=~\"$job\", alias=\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Author Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_author_status{job=~\"$job\", alias=~\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Author Rating",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "♥️" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_author_rating_total{job=~\"$job\", alias=~\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_free_disk_size{job=~\"$job\", alias=\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Book Genres",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Books" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(readarr_book_genres{job=~\"$job\", alias=\"$readarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Books Disk Size",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_book_disk_size_total{job=~\"$job\", alias=\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Book Rating",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "♥️" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_book_rating_total{job=~\"$job\", alias=~\"$readarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bazarr ${bazarr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "bazarr" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"bazarr\", alias=\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_build_time{job=~\"$job\", alias=\"$bazarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - bazarr_last_scrape{job=~\"$job\", alias=\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - bazarr_start_time{job=~\"$job\", alias=\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitored Media",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_movies_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bazarr_series_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wanted Media",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_wanted_movies_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bazarr_wanted_episodes_total{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Providers Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_providers{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Providers Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_provider_status{job=~\"$job\", alias=~\"$bazarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prowlarr ${prowlarr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }, "repeat": "prowlarr" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"prowlarr\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_build_time{job=~\"$job\", alias=\"$prowlarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prowlarr_last_scrape{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prowlarr_start_time{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_applications_total{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_application_enabled_total{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Sync-Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_application_sync_level_total{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_count{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled Indexers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_enabled{job=~\"$job\", indexer=\"total\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer Privacy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_indexer_privacy{job=~\"$job\", alias=\"$prowlarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer VIP Expire in",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_vip_expiration{job=~\"$job\", alias=\"$prowlarr\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sonarr ${sonarr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }, "repeat": "sonarr" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"sonarr\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_build_time{job=~\"$job\", alias=\"$sonarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sonarr_last_scrape{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sonarr_start_time{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total/Missing Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Episodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_missing_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total/Monitored/Ended/Continuing Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Series" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_monitored_series_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_ended_series{job=~\"$job\", path=\"total\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_continuing_series{job=~\"$job\", path=\"total\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_disk_size{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sonarr_disk_size_total{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_free_disk_size{job=~\"$job\", alias=\"$sonarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quality Episode",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Episode" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_quality_episodes_total{job=~\"$job\", alias=\"$sonarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genres Episode",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Episodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sonarr_genres_count_total{job=~\"$job\", alias=\"$sonarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Radarr ${radarr}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 }, "repeat": "radarr" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scraparr_services_up{job=~\"$job\", scraparr_services=\"radarr\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_build_time{job=~\"$job\", alias=\"$radarr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - radarr_last_scrape{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - radarr_start_time{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total/Downloaded/Monitored/Missing Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"} - radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_monitored_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_disk_size{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "radarr_disk_size_total{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_free_disk_size{job=~\"$job\", alias=\"$radarr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quality's",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_quality_movies_total{job=~\"$job\", alias=\"$radarr\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genres",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Movies" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(radarr_genres_count_total{job=~\"$job\", alias=\"$radarr\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}